---
- name: Deploying Application
  hosts: webservers
  become: True
  tasks:
    - name : Install System Packages
      apt:
        pkg: 
          - build-essential
          - python3-dev
          - python3-pip
          - python3-virtualenv
        state: present
        update_cache: yes             

    - name: Install NGINX Latest Version
      apt: name=nginx state=latest update_cache=yes
    
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/conf.d/default
      notify: restart nginx

    - name: Start NGINX 
      command: systemctl start nginx

    - name: Ensure NGINX launches on boot
      command: systemctl enable nginx

    - name: Create Virtual Environment
      command: virtualenv /root/ProjectEnv -p python3

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted