---
- name: Deploying Webserver
  hosts: webservers
  become: True
  tasks:
    - name: Install Latest Version of NGINX Web Server
      apt: name=nginx state=latest update_cache=yes
    
    - name: copy NGINX Configuration file
      copy: src=files/nginx.conf dest=/etc/nginx/conf.d/default
      notify: restart nginx

    - name: Ensure NGINX launches on boot
      command: systemctl enable nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted